$("head").append('<link rel="preconnect" href="https://fonts.googleapis.com">');
$("head").append('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>');
$("head").append('<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">');
$("head").append('<link href="./css/bootstrap.min.css" rel="stylesheet">');
$("head").append('<link href="./css/bootstrap-submenu.css" rel="stylesheet">');
$("head").append('<link href="./css/style-basic.css" rel="stylesheet">');
$("head").append('<link href="./css/style.css?v1" rel="stylesheet">');
$("head").append('<link href="./css/swiper-bundle.min.css" rel="stylesheet">');
$("head").append('<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">');
$("head").append('<link href="./css/aos.css" rel="stylesheet">');
$("head").append('<script src="./js/jquery-3.6.0.min.js"></script>');
$("head").append('<script src="./js/bootstrap.bundle.min.js"></script>');
$("head").append('<script src="./js/swiper-bundle.min.js"></script>');
$("head").append('<script src="./js/custom.js"></script>');
$("head").append('<script src="./js/bootstrap-submenu.js"></script>');
$("head").append('<script src="./js/aos.js"></script>');
